### ISSUE TITLE
Temperature reading is finicky

### ISSUE THREAD

**Issue by beaufour** [getopenmono/temperature#2]
There's something finicky about the temperature reading logic. It is read and used fine on the display, but even though it's the same logic in `internet_upload.cpp` the request almost always sends `65535`. The same value is also read when you touch the display to change between F and C, 65535 is displayed once and then the real temperature afterwards (when read on the normal cycle).

**Comment by beaufour** [comment]
Actually, I think I figured out what's going on. You'll only get the correct temperature if you read it twice :)

**Comment by jpsecher** [comment]
There is a bug in Mono Framework v1.2 that causes I<sup>2</sup>C communication go wrong.  We are releasing v1.3 with a fix in a few hours.

**Comment by beaufour** [comment]
ok, reading but meanwhile reading the value twice fixes it for me. https://github.com/beaufour/temperature/commit/826c19323f7a85c3919ecd5bf6909b475a1a3f18

**Comment by jpsecher** [comment]
https://github.com/getopenmono/openmono_package/releases/tag/SDKv1_3

**Comment by beaufour** [comment]
SDK 1.3 fixed the issue, thanks.
